# Generated by Django 4.2.5 on 2024-11-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Alumni',
        ),
    ]
