# Generated by Django 4.2.5 on 2024-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_orders_alumnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
